### ISSUE TITLE
Ender 3 fly board

### ISSUE THREAD

**Issue by Spanker-General** [Mellow-3D/FLY-RRF-E3#1]
Hello, I have been advised to leave my request for help here,  the firmware has been installed but on switching on the board immediately heated up to 109.5 (I switched it off) also z won't home. 
Could this be a firmware issue? I used the configurator, and firmware.bin for my board.

Appreciate any help

**Comment by jaysuk** [comment]
@Spanker-General did you get sorted?

**Comment by Spanker-General** [comment]
All is good @jaysuk all that is required is fine tuning
