### ISSUE TITLE
Request: Allow TMC2209 drivers with Diag pins to disable sensorless homing

### ISSUE THREAD

**Issue by disneytoy** [Mellow-3D/FLY-RRF-E3#2]
This board is targeted to Ender 3 owners were endstops are already installed. 

Unfortunately, I have several non Mellow TMC2209 drivers. I'd prefer not to cut the Diag pins because I will most likely move these to other boards later. There must be a way in the firmware, to just ignore the sensorless homing and allow just the real endstops? The end stop switches are triggering. Just send the sensorless homing trigger somewhere else. 

I'm sure many of us already have TMC2209s. I have a few Bigtree and some MKS.

I realize you can't change the hardware. You really should have added a jumper on each driver slot to enable the Diag pin. Would have cost nothing to do.. 

Thanks!

Max

**Comment by FLYmaker** [comment]
ok, when making the next batch of motherboards, I will think of ways to add on the motherboard
