### ISSUE TITLE
Disabling/Modifying bed temperature rising control

### ISSUE THREAD

**Issue by equipment66** [Mellow-3D/FLY-RRF-E3#4]
Hi.
I have installed FLY RRF E3 on my ender. This is my first experience with REPRAP.
Everything seems to work fine, except one thing: after starting bed heater, temperature rising up. After +- 30 sec bed heater sets to fault state with message: 
<html>
<body>

10/5/2021, 10:21:47 PM | Error: Heater 0 fault: temperature rising much more slowly than the expected 1.7°C/sec
-- | --

</body>
</html>

How to fix it or disable temperature rising speed check?

Thank you :)

**Comment by equipment66** [comment]
One more thing: rising speed for bed temperature seem to be correct. 1.7 degree per second could be ok for hot end, not for bed :)

**Comment by jaysuk** [comment]
Have you PID tuned the bed using M303 H0 S60?

**Comment by equipment66** [comment]
Of course that... not :) Thank you.
BTW, I found 2 more issues, sorry :)

**Comment by jaysuk** [comment]
I suggest you look here where you'll find all the information you need.
https://teamgloomy.github.io/fly_e3_general.html

**Comment by equipment66** [comment]
Thank you. I found answer about screen and will close issue. But I still have one question about Wifi.

**Comment by jaysuk** [comment]
Feel free to ask here but you'll get easier/quicker support on discord here
https://discord.gg/uS97Qs7

**Comment by equipment66** [comment]
Good time of the day, 

I’m sorry about disturbing you one more time, but I can not enter discord because very strange verification procedure. Which one looks like kind of phishing and seems to be unsafe. The system is asking me to enter password for never created account 😊
Could you maybe suggest support on more known and reliable recourses with clear login/verification procedure?

Geros dienos/Have a nice day,

Vilius Grinkevičius
GSM: +370 660 05003
