### ISSUE TITLE
Wi-Fi control from the screen

### ISSUE THREAD

**Issue by equipment66** [Mellow-3D/FLY-RRF-E3#6]
Hi.
I have already successfully started Wi-Fi.
However, I can not control wi-fi using screen. Wi-Fi control buttons on the last tab of the screen stays inactive.
I can enter user name and password, but can not on/off module and connect.

Is it possible to fix it?

Thanks.

**Comment by jaysuk** [comment]
No. The screen doesn't have wifi access like that.

**Comment by equipment66** [comment]
:( I'm traveling and need to change network very often. Should be useful. But whats to do.
Thank you and have good day! :)

**Comment by jaysuk** [comment]
You can use gcode control to send M587.
You could also set the printer in access point mode to broadcast its own IP
address that may be more suitable.
