### ISSUE TITLE
TFT35 Refresh and Reboot

### ISSUE THREAD

**Issue by apohl23** [Mellow-3D/FLY-RRF-E3#7]
Hello everyone, until a few days ago everything was running smoothly. Now I've recently had the problem that the TFT keeps rebooting after a certain time, and sometimes the screen is white. Is this an error in the system or in the firmware? I have the FLY E3 RRF v1.0 and the TFT35 V3.0 from BTT also configured for RRF. Both have the same baud rate and are connected to TX and RX GND and 5V according to the connection diagram.

I have also heard about this error from other colleagues.

We would be very pleased to receive an answer
Best regards from Germany
Andy

German

Hallo zusammen, bis vor ein paar tagen lief eingendlich alles einwandfrei. Jetzt habe ich seit kurzen das problem das, dass TFT nach einer gewissen zeit immer wieder neustartet, manchmal ist dann auch der Bildschirm weiß. Ist das ein Fehler im System oder in der Firmware. Ich habe das FLY E3 RRF v1.0 und von BTT das TFT35 V3.0 ebenfalls auf RRF Konfiguriert. Beide haben auch die gleich Baudrate und sind laut Anschlussplan mit TX und RX GND und 5V verbunden.

Ich habe auch von anderen Kollegen von diesen Fehler gehört.

Wir wären über eine Antwort sehr erfreut
Beste Grüße aus Deutschland
Andy

**Comment by jaysuk** [comment]
I would say its either a TFT firmware issue or you're pulling too much power from the 5v rail.
You could try and power the screen from its own 5v supply.
If that doesn't fix it then its a TFT firmware issue
